name: ad_spire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: fonts/GeneralSans-Italic.otf
          style: italic
        - asset: fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: fonts/GeneralSans-Semibold.otf
          weight: 700